language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

matrix:
  include:
  - php: '7.1'
  - php: '7.2'

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer global require --dev 'friendsofphp/php-cs-fixer:^2.11'
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - composer update --no-progress --no-suggest --ansi

script:
  - ./vendor/bin/phpunit tests
